language: java
deploy:
  api_key:
    secure: LIjc2hjjoIwRNpZpBjucKCRhSkIxvOp3AGxoYee5Ng55+tol7uJV78sfZgRYPytCAbFAUULsGpVdVal6Rt4d9N1eR0W/ZEc5WsUVXwwFW84HMoKJbnWjWdJhKqrAhvQUZlq8UOGNKaxmNRmzTb/f9gLC1THWT49poRCUTfMIQdwkwR1j5a5ta71j3T6OfEo9KGxbkeLYc8Qa02e0ed6j05D7UjpsgOM8g6ozin1PqQUspRWAsMDmIrnlMfhYtCKUbPju1K2+vcugVd15seTA59Nrg5qXJMjl60KZWxljzo61FfcQixMn481WngMFxwNKQzsgC7tIiEZ3cnV5uK/RiXTCKjYFhvYZYGqF0h7Y788cahpOpuNuyUXwkOntLJNvO11zt8CJ0hG5wn+BF2N8lcyQlYQCiazn4wnXaTGmAIB6rpoQGNkvhR8Kw91Ilx51VAdq0qei/zGuavds8SGp0GjmKX1zLd1PY9aUaoX/nJ/LdSCicIqfhJwTdjPG0ahzkFXdu47EFL266JwY75Kwz6dKb1e/Fw0qYx7AxOQT8jdkDnh8SDLQqE4O4MyOcqHU3hw5NEZKZDe32rNnqXIl8HYzA5lBzwLgIY6WRKk2Lk8uk5yqxL9gHj+5DlLFepSWS/WunJCQn7g/lS/c4Hp0nv0OUop8yaWdZ0TMuuUemKg=

  strategy: git
